# Generated by Django 4.0.4 on 2022-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_car_title_alter_car_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='car',
            name='text2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
