# Generated by Django 4.0.4 on 2022-05-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_car_text3'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='emblem',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
