# Generated by Django 4.0.4 on 2022-05-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Imgs',
        ),
    ]
